# # on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches: '*'

# name: Project check
# jobs:
#   check:
#     name: Check
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set up Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '16'

#     - uses: actions/checkout@master
#       name: Checkout

#     - name: Install dependencies
#       run: |
#         npm install

#     - name: Run checks
#       run: |
#         npm run lint


on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

name: Project check
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run checks
      run: npm run lint

  build:
    runs-on: ubuntu-latest
    # ВАЖНО: деплоим только при пуше в main или ручном запуске,
    # чтобы пулл-реквесты не ломали деплой
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: check # Сборка начнется только если линтер (check) прошел успешно
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm config set package-lock false
          npm install

      - name: Build Project
        run: npm run build

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
